services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - REDIS_URL=redis://default:password@redis:6379/0
    depends_on:
      - redis
    networks:
      - dokploy-network

  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: password
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    networks:
      - dokploy-network

volumes:
  db-data:

networks:
  dokploy-network:
    external: true
