services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - REDIS_URL=redis://default:password@redis:6379/0
      - CUSTOM_ENV=${CUSTOM_ENV}
    depends_on:
      - redis
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-app.rule=Host(`backend.neatapps.dev`)
      - traefik.http.routers.backend-app.entrypoints=web
      - traefik.http.services.backend-app.loadbalancer.server.port=5000

  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: password
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    networks:
      - dokploy-network

volumes:
  db-data:

networks:
  dokploy-network:
    external: true
